services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fintechco
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking_secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d fintechco"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
